const trackData = [
  { id: 1, title: "Dawn Township" },
  { id: 2, title: "GBA Cheep Cheep Island" },
  { id: 3, title: "ASDF_Course" },
  { id: 4, title: "Sky Shrine" },
  { id: 5, title: "Sunset Forest" },
  { id: 6, title: "Jungle Cliff" },
  { id: 7, title: "Kartwood Creek" },
  { id: 8, title: "Haunted Woods" },
  { id: 9, title: "GBA Broken Pier" },
  { id: 10, title: "SNES Choco Island 2" },
  { id: 11, title: "Rush City Run" },
  { id: 12, title: "Twin Peaks" },
  { id: 13, title: "DS Figure-8 Circuit" },
  { id: 14, title: "Galvarny Falls" },
  { id: 15, title: "DS Waluigi Pinball" },
  { id: 16, title: "GCN Daisy Cruiser" },
  { id: 17, title: "GBA Bowser Castle 4" },
  { id: 18, title: "Luncheon Tour" },
  { id: 19, title: "DS Wario Stadium" },
  { id: 20, title: "The Rabbit Hole" },
  { id: 21, title: "SNES Mario Circuit 1" },
  { id: 22, title: "Lakeside Hill" },
  { id: 23, title: "Sunset Circuit" },
  { id: 24, title: "DS Cheep Cheep Beach" },
  { id: 25, title: "GCN Yoshi Circuit" },
  { id: 26, title: "SNES Mario Circuit 2" },
  { id: 27, title: "N64 Royal Raceway" },
  { id: 28, title: "Candy Coaster" },
  { id: 29, title: "DS Airship Fortress" },
  { id: 30, title: "Yoshi Lagoon" },
  { id: 31, title: "N64 Choco Mountain" },
  { id: 32, title: "Summer Starville" },
  { id: 33, title: "Waluigi's Motocross" },
  { id: 34, title: "SNES Bowser Castle 2" },
  { id: 35, title: "GCN Bowser's Castle" },
  { id: 36, title: "Incendia Castle" },
  { id: 37, title: "Melting Magma Melee" },
  { id: 38, title: "Final Grounds" },
  { id: 39, title: "Pipe Underworld" },
  { id: 40, title: "Canyon Run" },
  { id: 41, title: "New Moon Manor" },
  { id: 42, title: "Nightlife Party" },
  { id: 43, title: "N64 Banshee Boardwalk" },
  { id: 44, title: "Fishdom Island" },
  { id: 45, title: "Toad Raceway" },
  { id: 46, title: "Spike Desert" },
  { id: 47, title: "Delfino Island" },
  { id: 48, title: "Six King Labyrinth" },
  { id: 49, title: "GCN Luigi Circuit" },
  { id: 50, title: "Unnamed Valley" },
  { id: 51, title: "Rockside River" },
  { id: 52, title: "Undiscovered Offlimit" },
  { id: 53, title: "Honeybee Hideout" },
  { id: 54, title: "Nostalgic Bowser's Castle" },
  { id: 55, title: "Rosalina's Snow World‎" },
  { id: 56, title: "DKR Star City" },
  { id: 57, title: "SNES Donut Plains 3" },
  { id: 58, title: "Skyline Avenue" },
  { id: 59, title: "GCN Wario Colosseum" },
  { id: 60, title: "Mushroom Peaks" },
  { id: 61, title: "Icecream Sweetland" },
  { id: 62, title: "Cottonplant Forest" },
  { id: 63, title: "Autumn Leavesway" },
  { id: 64, title: "GCN Sherbet Land" },
  { id: 65, title: "SNES Donut Plains 2" },
  { id: 66, title: "DS Tick-Tock Clock" },
  { id: 67, title: "Volcanic Skyway" },
  { id: 68, title: "Neo Koopa City" },
  { id: 69, title: "Infernal Pipeyard" },
  { id: 70, title: "Jungle Ruins" },
  { id: 71, title: "Cookie Village" },
  { id: 72, title: "CTR Cortex Castle" },
  { id: 73, title: "GBA Ribbon Road" },
  { id: 74, title: "DS Luigi's Mansion" },
  { id: 75, title: "Wolf Castlegrounds" },
  { id: 76, title: "Castle of Darkness" },
  { id: 77, title: "Nivurbia" },
  { id: 78, title: "DS Mario Circuit" },
  { id: 79, title: "Cave Island" },
  { id: 80, title: "Dark Matter Shrine" },
  { id: 81, title: "GBA Sky Garden" },
  { id: 82, title: "Glimmer Express Trains" },
  { id: 83, title: "Sunset Raceway" },
  { id: 84, title: "Desert Castle Raceway" },
  { id: 85, title: "Melody Sanctum" },
  { id: 86, title: "Wario's Shipwreck" },
  { id: 87, title: "GBA Cheese Land" },
  { id: 88, title: "Misty Ruins" },
  { id: 89, title: "Stargaze Summit" },
  { id: 90, title: "Sea Stadium" },
  { id: 91, title: "Calidae Desert" },
  { id: 92, title: "N64 Kalimari Desert" },
  { id: 93, title: "Winter Paradise" },
  { id: 94, title: "Kinoko Cave" },
  { id: 95, title: "GCN Baby Park" },
  { id: 96, title: "Desktop Dash" },
  { id: 97, title: "GBA Bowser Castle 1" },
  { id: 98, title: "Aura Metropolis" },
  { id: 99, title: "CTR Blizzard Bluff" },
  { id: 100, title: "Aquania" },
  { id: 101, title: "GBA Mario Circuit" },
  { id: 102, title: "Rezway" },
  { id: 103, title: "Sunset Ridge" },
  { id: 104, title: "N64 Moo Moo Farm" },
  { id: 105, title: "Warp Pipe Island" },
  { id: 106, title: "Abandoned Boardwalk" },
  { id: 107, title: "Gothic Castle" },
  { id: 108, title: "DK Ruins" },
  { id: 109, title: "GBA Lakeside Park" },
  { id: 110, title: "N64 Koopa Troopa Beach" },
  { id: 111, title: "Camp Kartigan" },
  { id: 112, title: "Mushroom Island" },
  { id: 113, title: "Desert Mushroom Ruins" },
  { id: 114, title: "GCN Mushroom City" },
  { id: 115, title: "Unfinished Mario Circuit" },
  { id: 116, title: "Slot Circuit" },
  { id: 117, title: "Piranha Plant Pipeline" },
  { id: 118, title: "Lava Lake" },
  { id: 119, title: "Dragon Burial Grounds" },
  { id: 120, title: "N64 Frappe Snowland" },
  { id: 121, title: "GBA Luigi Circuit" },
  { id: 122, title: "Wuhu Mountain" },
  { id: 123, title: "Dreamworld Cloudway" },
  { id: 124, title: "Hellado Mountain" },
  { id: 125, title: "Red Loop" },
  { id: 126, title: "Suzuka Circuit" },
  { id: 127, title: "Forest Creek" },
  { id: 128, title: "Dragonite's Island" },
  { id: 129, title: "Lunar Spaceway" },
  { id: 130, title: "Seaside Resort" },
  { id: 131, title: "GCN Mushroom Bridge" },
  { id: 132, title: "Yoshi's Woolly Raceway" },
  { id: 133, title: "GBA Boo Lake" },
  { id: 134, title: "Shadow Woods" },
  { id: 135, title: "Jiyuu Village" },
  { id: 136, title: "Windmill Village" },
  { id: 137, title: "Rock Rock Ridge" },
  { id: 138, title: "Christmas Court" },
  { id: 139, title: "Mansion of Madness" },
  { id: 140, title: "Big Nature City" },
  { id: 141, title: "SADX Twinkle Circuit" },
  { id: 142, title: "Galaxy Base" },
  { id: 143, title: "Alpine Peak" },
  { id: 144, title: "Celestial Ruins" },
  { id: 145, title: "SNES Bowser Castle 1" },
  { id: 146, title: "Luigi's Island" },
  { id: 147, title: "SNES Bowser Castle 3" },
  { id: 148, title: "Lava Road" },
  { id: 149, title: "Cool Castle Canyon" },
  { id: 150, title: "Jungle Jamble" },
  { id: 151, title: "Boshi Skatepark" },
  { id: 152, title: "Flowery Greenhouse" },
  { id: 153, title: "Crystal Plains" },
  { id: 154, title: "Underground Sky" },
  { id: 155, title: "DS DK Pass" },
  { id: 156, title: "GBA Snow Land" },
  { id: 157, title: "Secluded Island" },
  { id: 158, title: "Hell Pyramid" },
  { id: 159, title: "Headlong Skyway" },
  { id: 160, title: "White Garden" },
  { id: 161, title: "Colour Wonderland" },
  { id: 162, title: "N64 Luigi Raceway" },
  { id: 163, title: "Volcanic Valley" },
  { id: 164, title: "Sahara Hideout" },
  { id: 165, title: "Seasonal Circuit" },
  { id: 166, title: "Comet Starway" },
  { id: 167, title: "Shy Guy's Market" },
  { id: 168, title: "Festival Town" },
  { id: 169, title: "Cherry Blossom Garden" },
  { id: 170, title: "Sky Grove" },
  { id: 171, title: "Tropical Factory" },
  { id: 172, title: "Crystal Dungeon" },
  { id: 173, title: "Aquadrom Stage" },
  { id: 174, title: "Abyssal Ruins" },
  { id: 175, title: "Kirio Raceway" },
  { id: 176, title: "Icepeak Mountain" },
  { id: 177, title: "GBA Sunset Wilds" },
  { id: 178, title: "DKR Ancient Lake" },
  { id: 179, title: "N64 Toad's Turnpike" },
  { id: 180, title: "N64 Wario Stadium" },
  { id: 181, title: "GCN Dry Dry Desert" },
  { id: 182, title: "GBA Riverside Park" },
  { id: 183, title: "Volcanic Pipeyard" },
  { id: 184, title: "Concord Town" },
  { id: 185, title: "Big Express City" },
  { id: 186, title: "Lost Fortress" },
  { id: 187, title: "DKR Jungle Falls" },
  { id: 188, title: "Colour Circuit" },
  { id: 189, title: "DS Bowser Castle" },
  { id: 190, title: "DS Shroom Ridge" },
  { id: 191, title: "GBA Peach Circuit" },
  { id: 192, title: "GBA Rainbow Road" },
  { id: 193, title: "Halogen Highway" },
  { id: 194, title: "Item Fireland" },
  { id: 195, title: "Daisy Hillside" },
  { id: 196, title: "Seaside Circuit" },
  { id: 197, title: "Bayside Boulevard" },
  { id: 198, title: "SNES Donut Plains 1" },
  { id: 199, title: "Sinister Vault" },
  { id: 200, title: "Wetland Woods" },
  { id: 201, title: "Volcanic Skyway 4" },
  { id: 202, title: "GP Mario Beach" },
  { id: 203, title: "Bowser's Fiery Fortress" },
  { id: 204, title: "GBA Bowser Castle 2" },
  { id: 205, title: "SNES Ghost Valley 1" },
  { id: 206, title: "SNES Koopa Beach 2" },
  { id: 207, title: "Rainbow Road: Solar Edition" },
  { id: 208, title: "Castle of Time" },
  { id: 209, title: "Thwomp Swamp" },
  { id: 210, title: "Marble Towers" },
  { id: 211, title: "Heart of China" },
  { id: 212, title: "Koopa Shell Pipeland" },
  { id: 213, title: "Flying Kingdom" },
  { id: 214, title: "Lunar Lights" },
  { id: 215, title: "GCN Rainbow Road" },
  { id: 216, title: "SNES Rainbow Road 4" },
  { id: 217, title: "Star Slope" },
  { id: 218, title: "N64 Rainbow Road" },
];
export { trackData };
